name: infra-start

on: 
  workflow_dispatch
 # pull_request:
  #  types: 
   #   - closed
jobs:
  if_merged:
    name: if_merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
# Clonning repos
      - name: 'Checkout source repo'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      
      - name: 'Py Setup'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 'Start script'
        env:
            OWNER: "SVestor"
            REPO: "flux-cmp"
            github_webhook_token: '${{ secrets.GH_PAT }}'
        run: |- 
          pip install -r requirements.txt
          python gh_dispatches.py
